"""agregar campos bold y dropi a orders y products

Revision ID: 7ea90d93ebc9
Revises: 5f49364d06e9
Create Date: 2026-07-17 01:27:35.207793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea90d93ebc9'
down_revision: Union[str, Sequence[str], None] = '5f49364d06e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('orders', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('orders', 'department_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('orders', 'city_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_constraint(op.f('orders_bold_order_id_key'), 'orders', type_='unique')
    op.create_index(op.f('ix_orders_bold_order_id'), 'orders', ['bold_order_id'], unique=True)
    op.drop_column('orders', 'customer_email')
    op.drop_column('orders', 'customer_name')
    op.alter_column('store_layout', 'page_slug',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'home'::character varying"))
    op.drop_index(op.f('ix_store_layout_page_slug'), table_name='store_layout')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_store_layout_page_slug'), 'store_layout', ['page_slug'], unique=False)
    op.alter_column('store_layout', 'page_slug',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'home'::character varying"))
    op.add_column('orders', sa.Column('customer_name', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('customer_email', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_orders_bold_order_id'), table_name='orders')
    op.create_unique_constraint(op.f('orders_bold_order_id_key'), 'orders', ['bold_order_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('orders', 'city_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('orders', 'department_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('orders', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
